### PR TITLE
Updated Avatar.js & botinfo.js, added ServerIcon.js

### PR DESCRIPTION
**Pull request by L0SER8228**
Updated avatar commad. Better avatar quality. Now we can use use user id, mention a user to get his pfp. If no args is provided it will return author pfp.
Servericon commad added. Returns current server logo.
Updated botinfo commad. New info code added

### CODE REVIEW

**Comment by Aktindo** [comment]
> Updated avatar commad. Better avatar quality. Now we can use use user id, mention a user to get his pfp. If no args is provided it will return author pfp.
> Servericon commad added. Returns current server logo.
> Updated botinfo commad. New info code added

Oh hi there! Well, I didn't notice this until I got a mail from GitHub but it seems good! We will verify the code and let you know when the verification is complete! Thank You for contributing to this project.

**Comment by Aktindo** [comment]
> Updated avatar commad. Better avatar quality. Now we can use use user id, mention a user to get his pfp. If no args is provided it will return author pfp.
> Servericon commad added. Returns current server logo.
> Updated botinfo commad. New info code added

There seems to be an issue with the code rn but will fix it later! Thanks anyways

**Comment by Aktindo** [comment]
According to the style of the code, we are using, and according to the new updates we made, this won't work, unfortunately. All the commands are working but I would have to change some things here and there! Thanks for this and now I am merging the commands that can be merged without any conflict!

**Comment by L0SER8228** [comment]
Ohhk

**Comment by Aktindo** [comment]
done! closing the request

**Pull request merged**
