### PR TITLE
Add Kick, Ban Command

### PR DESCRIPTION
**Pull request by iamgobinda**
i have created kick and ban command. Who have kick, ban permission , he can kick ,ban a member. it also send a dm to the kickuser, banuser. You can use user id or mention him to ban.

### CODE REVIEW

**Comment by YT-GameWorks** [comment]
Nice ! I will implement it after a few changes... My code style for js is a littel diffrent as I am a mainly a Java and a c# programmer :)

**Comment by Aktindo** [comment]
> i have created kick and ban command. Who have kick, ban permission , he can kick ,ban a member. it also send a dm to the kickuser, banuser. You can use user id or mention him to ban.

Hey thanks a lot man! we will merge that once I verify if the code is working! 😄

**Comment by iamgobinda** [comment]
May be the code style is different but i have tested it. it is working.
I am very happy to contribute 🙂

**Comment by YT-GameWorks** [comment]
Thanks ! Merged it

**Pull request closed without merging**
